<robot name="camera" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- * Template: Camera -->
    <xacro:property name="camera_length" value="0.03" />
    <xacro:property name="camera_width" value="0.01" />
    <xacro:property name="camera_height" value="0.02" />
    <xacro:property name="camera_mass" value="0.01" />

    <xacro:macro name="add_camera" params="x_offset">
        <link name="camera">
            <visual>
                <geometry>
                    <box size="${camera_length} ${camera_width} ${camera_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 ${PI / 2}" />
                <material name="laser_support_material">
                    <color rgba="0.3 0.9 0.3 0.9" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.03 0.01 ${camera_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 ${PI / 2}" />
            </collision>
            <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}"
                h="${camera_height}" />
        </link>

        <joint name="camera_2base" type="fixed">
            <parent link="base_link"></parent>
            <child link="camera"></child>
            <origin
                xyz="${base_link_radius - x_offset} 0 ${base_link_length / 2 + camera_height / 2}"
                rpy="0 0 0" />
        </joint>

        <gazebo reference="camera">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <xacro:add_camera x_offset="0.02" />
</robot>